version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/"
    schedule:
      interval: "monthly"
    reviewers:
      - "gliff-ai/ci-cd"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: "npm"
    # ignore all minor and patch updates as these will be caught by gliff-ai-robot
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "gliff-ai/frontend"
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-minor", "version-update:semver-patch"]
  - package-ecosystem: "npm"
    # update gliff packages very regularly
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "gliff-ai/frontend"
    ignore:
      - dependency-name: "@gliff-ai/*"
